### ISSUE TITLE
Weird calculation of part3 in 'sample_k_v_gl_loc()' method

### ISSUE THREAD

**Issue by bab2min** [yinfeiy/MG-LDA#2]
Thanks for sharing good code. I found some mistake in code. In Line 271 of MGLDA.java (sample_k_v_gl_loc() method),
part3 is calculated like below:
`part3 = (this.ndv_loc[doc_id][sent_id+v] + this.beta_loc) / (this.ndv[doc_id][sent_id+v] + this.alpha_mix_gl + this.alpha_mix_loc);
`

It is pi probability calculation about alpha_mix, but hyperparameter **beta_loc** is used. I think that line should be fixed like:
`part3 = (this.ndv_loc[doc_id][sent_id+v] + this.alpha_mix_loc) / (this.ndv[doc_id][sent_id+v] + this.alpha_mix_gl + this.alpha_mix_loc);
`

(Fortunately, since alpha_mix_loc == beta_loc in this code currently, the result of estimation would be the same.)

**Comment by yinfeiy** [comment]
Thanks for pointing it out. It is fixed.
